import { Outfit } from 'next/font/google';
import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';

const outfit = Outfit({
  subsets: ['latin'], // Choose the required subsets
  weight: ['400', '500', '700'], // Specify font weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
